In [57]:
import pandas as pd

# Load the CSV file
file_path = 'content/distinct_buildings excel.csv'  # Adjust the file path if needed
data = pd.read_csv(file_path, delimiter=';')

# Check if 'location' column exists
if 'location' in data.columns:
    # Split the 'location' column into 'latitude' and 'longitude'
    data[['latitude', 'longitude']] = data['location'].str.split(',', expand=True)

    # Optionally, you can drop the original 'location' column
    data.drop(columns=['location'], inplace=True)
    data.drop(columns=['Column1'], inplace=True)
    data.rename(columns={
    'building': 'building_code'}, inplace=True)
    # Save the modified DataFrame to a new CSV file
    new_file_path = 'content/distinct_buildings_modified.csv'
    data.to_csv(new_file_path, index=False, sep=';')

    print("File processed and saved as:", new_file_path)
else:
    print("The 'location' column was not found in the CSV file.")

File processed and saved as: content/distinct_buildings_modified.csv

In [58]:
data

   building_code            latitude            longitude
0             ZI   52.23920253719435    6.856910817479597
1             CR   52.23816328226085    6.857637461359666
2             HT   52.23761533457211    6.860704629276648
3             RA  52.239394466454705    6.855659446986793
4             CU    52.2404747275504    6.856748790412035
5             SP   52.23967014713761    6.849788127854926
6             SC   52.24387520603568    6.850267866916351
7             NH   52.23808480549669    6.861725240099451
8             OH   52.23695706050182    6.861045395561615
9             HB   52.23872999804916    6.857130329481763
10            WA   52.23847743019222   6.8563891284821175
11            WH   52.23871000853758    6.859747131536082
12            HR   52.23762429639754    6.860899781564861
13            VR   52.24380877424921    6.853376992143756
14            CI   52.23889678656126    6.855166303367093
15            EX   52.23889678656126    6.855166303367093
16            GY  52.237232702978964   6.8550384228553325
17            TH  52.236476928219574    6.843190805386873

In [53]:
from sqlalchemy import create_engine
import pandas as pd

driver = 'postgresql'
username = 'dab_ds23241a_123'
dbname = username  # it is the same as the username
password = 'BdleaEuFH036h8hi'
server = 'bronto.ewi.utwente.nl'
port = '5432'
# Creating the connection pool for SQL
engine = create_engine(f'{driver}://{username}:{password}@{server}:{port}/{dbname}?client_encoding=utf8')

sql_query = 'SELECT * FROM timetables.activities'

# Use pandas to execute the query and load results into a DataFrame
activities = pd.read_sql_query(sql_query, engine)

In [54]:
activities

,course_code,activity_name,start_time,end_time,year,activity_description,activity_type,duration,date,room,building_code,program_code,distance_to_next_activity_km
0,191210750,1B System-on-chip-Design/HC01/01,08:45:00,12:30:00,2013,191210750 System-on-chip-Design,PRA,3.75,2013-11-11,ZI W3,ZI,EE M,NaN
1,191210750,1B System-on-chip-Design/HC01/01,08:45:00,12:30:00,2013,191210750 System-on-chip-Design,PRA,3.75,2013-11-11,ZI W4,ZI,EE M,NaN
2,191210750,1B System-on-chip-Design/HC05/01,08:45:00,12:30:00,2013,191210750 System-on-chip-Design,PRA,3.75,2013-11-18,ZI W3,ZI,EE M,NaN
3,191210750,1B System-on-chip-Design/HC05/01,08:45:00,12:30:00,2013,191210750 System-on-chip-Design,PRA,3.75,2013-11-18,ZI W4,ZI,EE M,NaN
4,191210750,1B System-on-chip-Design/HC02/01,13:45:00,17:30:00,2013,191210750 System-on-chip-Design,PRA,3.75,2013-11-11,ZI W3,ZI,EE M,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147743,201600172,Project/PRS01/01,10:45:00,12:30:00,2016,Project,PRS,1.75,2017-02-03,SP 2,SP,IBA B,NaN
147744,201600198,Molecular spectroscopy for imaging/HC01/01,13:45:00,15:30:00,2016,Molecular spectroscopy for imaging,HC,1.75,2016-11-14,HB 2B,HB,BMT B,NaN
147745,201600198,Magnetic Resonance Imaging/TOETS02/01,08:45:00,11:45:00,2016,Magnetic Resonance Imaging,TOETS,3.00,2017-01-13,ZZ CR 2G/T,CR,BMT B,NaN
147746,201600198,Molecular spectroscopy for imaging/RESP01/01,10:45:00,12:30:00,2016,Molecular spectroscopy for imaging,RES,1.75,2017-01-23,HB 2B,HB,BMT B,NaN
147747,201600198,Project Imaging & Diagnostics/PRS01/01,09:45:00,12:30:00,2016,Project Project Imaging & Diagnostics,PRS,2.75,2017-02-02,CR 3A,CR,BMT B,NaN

In [59]:
activities = activities.merge(data, left_on='building_code', right_on='building_code', how='left')

In [60]:
activities

,course_code,activity_name,start_time,end_time,year,activity_description,activity_type,duration,date,room,building_code,program_code,distance_to_next_activity_km,latitude,longitude
0,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,NaN,52.23695706050182,6.861045395561615
1,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,NaN,52.23695706050182,6.861045395561615
2,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,NaN,52.23695706050182,6.861045395561615
3,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,0.0,52.23695706050182,6.861045395561615
4,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,0.0,52.23695706050182,6.861045395561615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147743,201600198,Magnetic Resonance Imaging/TOETS02/01,08:45:00,11:45:00,2016,Magnetic Resonance Imaging,TOETS,3.00,2017-01-13,ZZ CR 2G/T,CR,BMT B,NaN,52.23816328226085,6.857637461359666
147744,201600198,Molecular spectroscopy for imaging/RESP01/01,10:45:00,12:30:00,2016,Molecular spectroscopy for imaging,RES,1.75,2017-01-23,HB 2B,HB,BMT B,NaN,52.23872999804916,6.857130329481763
147745,201600198,Molecular spectroscopy for imaging/RESP01/01,10:45:00,12:30:00,2016,Molecular spectroscopy for imaging,RES,1.75,2017-01-23,HB 2B,HB,BMT B,NaN,52.23872999804916,6.857130329481763
147746,201600198,Project Imaging & Diagnostics/PRS01/01,09:45:00,12:30:00,2016,Project Project Imaging & Diagnostics,PRS,2.75,2017-02-02,CR 3A,CR,BMT B,NaN,52.23816328226085,6.857637461359666
147747,201600198,Project Imaging & Diagnostics/PRS01/01,09:45:00,12:30:00,2016,Project Project Imaging & Diagnostics,PRS,2.75,2017-02-02,CR 3A,CR,BMT B,NaN,52.23816328226085,6.857637461359666

In [61]:
# import pandas as pd
# from geopy.distance import geodesic
#
# # Assuming 'activities_df' is your DataFrame with the activities data
# # Make sure to load or define 'activities_df' here if it's not already loaded
#
# # First, sort the DataFrame to ensure activities are ordered correctly
# activities.sort_values(by=['course_code', 'program_code', 'year', 'date', 'start_time'], inplace=True)
#
# # Function to calculate distances
# def calculate_distances(row, next_row):
#     # Check if the next activity meets the criteria to calculate distance
#     if (row['course_code'] == next_row['course_code'] and
#         row['program_code'] == next_row['program_code'] and
#         row['year'] == next_row['year'] and
#         row['date'] == next_row['date']):
#         # Calculate and return the distance
#         return geodesic((row['latitude'], row['longitude']), (next_row['latitude'], next_row['longitude'])).kilometers
#     # Return None or 0 if criteria are not met
#     return None
#
# # Initialize a list to store calculated distances
# distances = []
#
# # Iterate through the DataFrame
# for i in range(len(activities) - 1):
#     # Calculate distance to next activity if criteria are met
#     distance = calculate_distances(activities.iloc[i], activities.iloc[i + 1])
#     distances.append(distance)
#
# # Append None for the last activity of each set, as it has no next activity
# distances.append(None)
#
# # Assign calculated distances to the DataFrame
# activities['distance_to_next_activity_km'] = distances
#
# # Optionally, save the updated DataFrame to a new CSV file
# new_file_path = 'updated_activities_with_distances.csv'
# activities.to_csv(new_file_path, index=False, sep=';')
#
# print("Updated file processed and saved as:", new_file_path)

Updated file processed and saved as: updated_activities_with_distances.csv

In [66]:
from geopy.distance import geodesic
# # First, sort the DataFrame to ensure activities are ordered correctly
activities.sort_values(by=['course_code', 'program_code', 'year', 'date', 'start_time'], inplace=True)

def calculate_distances(row, next_row):
    # Check if the next activity meets the criteria to calculate distance
    if (row['course_code'] == next_row['course_code'] and
        row['program_code'] == next_row['program_code'] and
        row['year'] == next_row['year'] and
        row['date'] == next_row['date']):

        # Check if consecutive activities have the same description
        if row['activity_description'] == next_row['activity_description']:
            return None  # Set distance to None if descriptions match

        # Calculate and return the distance
        return geodesic((row['latitude'], row['longitude']),
                        (next_row['latitude'], next_row['longitude'])).kilometers
    # Return None if criteria for same course, program, year, and date are not met
    return None

# Initialize a list to store calculated distances
distances = []

# Iterate through the DataFrame
for i in range(len(activities) - 1):
    # Calculate distance to next activity if criteria are met
    distance = calculate_distances(activities.iloc[i], activities.iloc[i + 1])
    distances.append(distance)

# Append None for the last activity of each set, as it has no next activity
distances.append(None)

# Assign calculated distances to the DataFrame
activities['distance_to_next_activity_km'] = distances

In [70]:
activities

,course_code,activity_name,start_time,end_time,year,activity_description,activity_type,duration,date,room,building_code,program_code,distance_to_next_activity_km,latitude,longitude
0,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,NaN,52.23695706050182,6.861045395561615
1,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,NaN,52.23695706050182,6.861045395561615
2,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,NaN,52.23695706050182,6.861045395561615
3,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,NaN,52.23695706050182,6.861045395561615
4,191100010,3B TRIZ - Fundamentals/HC01/01,08:45:00,17:30:00,2013,TRIZ - Fundamentals 191100010,HC,8.75,2014-07-07,OH 215,OH,IO B,NaN,52.23695706050182,6.861045395561615
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147743,201600198,Magnetic Resonance Imaging/TOETS02/01,08:45:00,11:45:00,2016,Magnetic Resonance Imaging,TOETS,3.00,2017-01-13,ZZ CR 2G/T,CR,BMT B,NaN,52.23816328226085,6.857637461359666
147744,201600198,Molecular spectroscopy for imaging/RESP01/01,10:45:00,12:30:00,2016,Molecular spectroscopy for imaging,RES,1.75,2017-01-23,HB 2B,HB,BMT B,NaN,52.23872999804916,6.857130329481763
147745,201600198,Molecular spectroscopy for imaging/RESP01/01,10:45:00,12:30:00,2016,Molecular spectroscopy for imaging,RES,1.75,2017-01-23,HB 2B,HB,BMT B,NaN,52.23872999804916,6.857130329481763
147746,201600198,Project Imaging & Diagnostics/PRS01/01,09:45:00,12:30:00,2016,Project Project Imaging & Diagnostics,PRS,2.75,2017-02-02,CR 3A,CR,BMT B,NaN,52.23816328226085,6.857637461359666
147747,201600198,Project Imaging & Diagnostics/PRS01/01,09:45:00,12:30:00,2016,Project Project Imaging & Diagnostics,PRS,2.75,2017-02-02,CR 3A,CR,BMT B,NaN,52.23816328226085,6.857637461359666

In [ ]:
activities = activities.drop('latitude',axis=1)

activities = activities.drop('longitude',axis=1)

In [ ]:
activities

In [71]:
from sqlalchemy import create_engine

driver = 'postgresql'
username = 'dab_ds23241a_123'
dbname = username  # it is the same as the username
password = 'BdleaEuFH036h8hi'
server = 'bronto.ewi.utwente.nl'
port = '5432'
# Creating the connection pool for SQL
engine = create_engine(f'{driver}://{username}:{password}@{server}:{port}/{dbname}?client_encoding=utf8')

# data.to_sql('buildings', con=engine, schema='timetables', if_exists='append', index=False, method='multi')
# activities.to_sql('activities', con=engine, schema='timetables', if_exists='append', index=False, method='multi')

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "latitude" of relation "activities" does not exist
LINE 1: ...code, program_code, distance_to_next_activity_km, latitude, ...
                                                             ^

[SQL: INSERT INTO timetables.activities (course_code, activity_name, start_time, end_time, year, activity_description, activity_type, duration, date, room, building_code, program_code, distance_to_next_activity_km, latitude, longitude) VALUES (%(course_cod ... 330235 characters truncated ... %(program_code__999)s, %(distance_to_next_activity_km__999)s, %(latitude__999)s, %(longitude__999)s)]
[parameters: {'latitude__0': '52.23695706050182', 'activity_description__0': 'TRIZ - Fundamentals 191100010', 'date__0': datetime.date(2014, 7, 7), 'activity_name__0': '3B TRIZ - Fundamentals/HC01/01', 'program_code__0': 'IO B', 'distance_to_next_activity_km__0': None, 'activity_type__0': 'HC', 'longitude__0': ' 6.861045395561615', 'room__0': 'OH 215', 'building_code__0': 'OH', 'start_time__0': datetime.time(8, 45), 'year__0': '2013', 'course_code__0': '191100010', 'duration__0': 8.75, 'end_time__0': datetime.time(17, 30), 'latitude__1': '52.23695706050182', 'activity_description__1': 'TRIZ - Fundamentals 191100010', 'date__1': datetime.date(2014, 7, 7), 'activity_name__1': '3B TRIZ - Fundamentals/HC01/01', 'program_code__1': 'IO B', 'distance_to_next_activity_km__1': None, 'activity_type__1': 'HC', 'longitude__1': ' 6.861045395561615', 'room__1': 'OH 215', 'building_code__1': 'OH', 'start_time__1': datetime.time(8, 45), 'year__1': '2013', 'course_code__1': '191100010', 'duration__1': 8.75, 'end_time__1': datetime.time(17, 30), 'latitude__2': '52.23695706050182', 'activity_description__2': 'TRIZ - Fundamentals 191100010', 'date__2': datetime.date(2014, 7, 7), 'activity_name__2': '3B TRIZ - Fundamentals/HC01/01', 'program_code__2': 'IO B', 'distance_to_next_activity_km__2': None, 'activity_type__2': 'HC', 'longitude__2': ' 6.861045395561615', 'room__2': 'OH 215', 'building_code__2': 'OH', 'start_time__2': datetime.time(8, 45), 'year__2': '2013', 'course_code__2': '191100010', 'duration__2': 8.75, 'end_time__2': datetime.time(17, 30), 'latitude__3': '52.23695706050182', 'activity_description__3': 'TRIZ - Fundamentals 191100010', 'date__3': datetime.date(2014, 7, 7), 'activity_name__3': '3B TRIZ - Fundamentals/HC01/01', 'program_code__3': 'IO B' ... 14900 parameters truncated ... 'start_time__996': datetime.time(15, 45), 'year__996': '2013', 'course_code__996': '191103250', 'duration__996': 1.75, 'end_time__996': datetime.time(17, 30), 'latitude__997': '52.23761533457211', 'activity_description__997': 'Project F 191103250', 'date__997': datetime.date(2014, 3, 24), 'activity_name__997': '2A Project F/HC04/01', 'program_code__997': 'WB B', 'distance_to_next_activity_km__997': None, 'activity_type__997': 'HC', 'longitude__997': ' 6.860704629276648', 'room__997': 'HT 1100', 'building_code__997': 'HT', 'start_time__997': datetime.time(15, 45), 'year__997': '2013', 'course_code__997': '191103250', 'duration__997': 1.75, 'end_time__997': datetime.time(17, 30), 'latitude__998': '52.23761533457211', 'activity_description__998': 'Project F 191103250', 'date__998': datetime.date(2014, 3, 24), 'activity_name__998': '2A Project F/HC04/01', 'program_code__998': 'WB B', 'distance_to_next_activity_km__998': None, 'activity_type__998': 'HC', 'longitude__998': ' 6.860704629276648', 'room__998': 'HT 1100', 'building_code__998': 'HT', 'start_time__998': datetime.time(15, 45), 'year__998': '2013', 'course_code__998': '191103250', 'duration__998': 1.75, 'end_time__998': datetime.time(17, 30), 'latitude__999': '52.23761533457211', 'activity_description__999': 'Project F 191103250', 'date__999': datetime.date(2014, 3, 24), 'activity_name__999': '2A Project F/HC04/01', 'program_code__999': 'WB B', 'distance_to_next_activity_km__999': None, 'activity_type__999': 'HC', 'longitude__999': ' 6.860704629276648', 'room__999': 'HT 1100', 'building_code__999': 'HT', 'start_time__999': datetime.time(15, 45), 'year__999': '2013', 'course_code__999': '191103250', 'duration__999': 1.75, 'end_time__999': datetime.time(17, 30)}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
import matplotlib.pyplot as plt
activities['distance_to_next_activity_km'].dropna().hist(bins=50)
plt.xlabel('Distance (km)')
plt.ylabel('Frequency')
plt.title('Distribution of Activity Distances')
plt.show()